version: '3'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - GEMINI_API_KEY=your_gemini_api_key
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
